"""ad images to articles

Revision ID: 1a77bb947a38
Revises: 579d7a02eafa
Create Date: 2024-01-05 00:28:16.796935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a77bb947a38'
down_revision: Union[str, None] = '579d7a02eafa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('articles', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('image', sa.VARCHAR(), nullable=True))
    op.drop_table('images')
    # ### end Alembic commands ###
