"""ad time utc+5 to user and to article

Revision ID: 1bce0196597a
Revises: edfcf2a63ed3
Create Date: 2024-01-01 00:21:24.875366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bce0196597a'
down_revision: Union[str, None] = 'edfcf2a63ed3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('categories', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'created_at')
    op.drop_column('articles', 'created_at')
    # ### end Alembic commands ###
