"""ad image

Revision ID: 1e27a2be1cf0
Revises: 9484be81530f
Create Date: 2024-01-04 18:00:08.644400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e27a2be1cf0'
down_revision: Union[str, None] = '9484be81530f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'image')
    # ### end Alembic commands ###
