"""delete photo

Revision ID: 98faabc3db77
Revises: bf350d0524c2
Create Date: 2023-12-31 20:09:41.083358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98faabc3db77'
down_revision: Union[str, None] = 'bf350d0524c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'photo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('photo', sa.VARCHAR(), server_default=sa.text("('')"), nullable=False))
    # ### end Alembic commands ###
