"""ad photo

Revision ID: b115e991d079
Revises: 8983ee56e5a5
Create Date: 2023-12-30 19:07:04.414281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b115e991d079'
down_revision: Union[str, None] = '8983ee56e5a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('photo', sa.String(), server_default='', nullable=False))
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.VARCHAR(), server_default=sa.text("('')"), nullable=False))
    op.drop_column('users', 'photo')
    # ### end Alembic commands ###
