"""delete phone from user

Revision ID: dc3d950437dc
Revises: daab54a0b682
Create Date: 2023-12-25 14:25:59.028087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc3d950437dc'
down_revision: Union[str, None] = 'daab54a0b682'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
