"""delete category

Revision ID: e214fdfd887d
Revises: 69227a50992c
Create Date: 2023-12-28 14:02:06.664647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e214fdfd887d'
down_revision: Union[str, None] = '69227a50992c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('category', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
